kafka :
  zookeeper.connect : localhost:2181
  group.id : "kafka-to-riemann"
  consumer.id : "kafka-to-riemann"
  topic : "test"
  auto.commit.interval.ms : "5000"
riemann :
  host     : localhost
  port     : 5555
